# Generated by Django 4.2 on 2023-10-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
