# Generated by Django 4.2 on 2023-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0011_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(unique=True)),
                ('time', models.TimeField()),
                ('tableNumber', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('paid', 'Paid')], max_length=10)),
                ('items', models.JSONField()),
            ],
        ),
    ]
