# Generated by Django 4.2 on 2023-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('ready', 'Ready'), ('paid', 'Paid')], max_length=10),
        ),
    ]
