# Generated by Django 4.2 on 2023-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0016_dish_service_charge_percentage_dish_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
