# Generated by Django 4.2 on 2023-11-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0017_alter_itemtransfer_transfer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='service_charge_percentage',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='tax_percentage',
        ),
    ]
