# Generated by Django 4.2 on 2023-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0019_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
