# Generated by Django 4.2 on 2023-11-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0022_alter_item_price_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
