# Generated by Django 4.2 on 2023-11-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0024_item_quantity_item_threshold_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
