# Generated by Django 4.2 on 2023-11-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0025_alter_item_quantity_alter_item_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
