# Generated by Django 4.2 on 2023-11-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsrest', '0030_alter_dishitem_quantity_alter_dishrecipe_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='totalcost',
            new_name='totalprice',
        ),
    ]
